### PR TITLE
ci: set it up

### PR DESCRIPTION
**Pull request by Thomaash**
Addresses #1, #12, #13.

### CODE REVIEW

**Comment by Thomaash** [comment]
Hi @mojoaxel, it seems that I can't publish this package on npm: `403 Forbidden - PUT https://registry.npmjs.org/vis-graph3d - You do not have permission to publish "vis-graph3d". Are you logged in as the correct user?`. Could you have a look at it please?

**Comment by mojoaxel** [comment]
>  it seems that I can't publish this package on npm

I just added you to the "graph3d" team.

**Comment by Thomaash** [comment]
Thanks, I'll restart the build and see if it works.

**Comment by mojoaxel** [comment]
Do we need to add "vis-bot" also to npm?

**Comment by Thomaash** [comment]
We don't need to but I think we should. It will be better than having my name under all the automatic releases.

**Comment by mojoaxel** [comment]
@Thomaash Could you please create a new user on npmjs.org for our vis-bot! :pray: 
I hope you have enough rights already to manage the [visjs orga on npm](https://www.npmjs.com/settings/visjs/teams). If not please talk to me.

**Comment by Thomaash** [comment]
So vis-bot is on npm but I can't invite people into visjs organization.

**Comment by mojoaxel** [comment]
> So vis-bot is on npm but I can't invite people into visjs organization.

I send an invite.
(@Thomaash Could you please send me the credetials for the vis-bot npm login wie gpg-email.. Thx!!)

**Pull request merged**
