### PR TITLE
Issue templates

### PR DESCRIPTION
**Pull request by mojoaxel**

### CODE REVIEW

**Comment by mojoaxel** [comment]
@Thomaash @yotamberk and every one else here: Could you please review this, I would like to introduce this to the other repositories in the visjs-family as well...If you like it..

**Comment by yotamberk** [comment]
Seems good to me.
I would add though some comment requesting (or even demanding) a `jsbin` or reproducible example. This makes my time WAY easier when fixing bugs.

**Comment by mojoaxel** [comment]
@yotamberk I added a Section `example code` instead of `screenshots`. Please review!

**Comment by mojoaxel** [comment]
@visjs/maintainer Please review! I would like to merge this here and later to all the repositories.

**Pull request merged**
